remote_theme: chrisrhymes/bulma-clean-theme
title: Live Coding in Python
google_analytics: UA-4644630-2
favicon: https://donkirkby.github.io/favicon.png

defaults:
  - scope:
      path: ""
    values:
      hero_image: images/index_hero.jpg
      hero_darken: True
      twitter:
        card: summary_large_image
      image: images/index_hero.jpg
